packages:
  - "apps/*"
  - "packages/*"

catalog:
  "dayjs": "^1.11.13"
  "embla-carousel-react": "^8.6.0"
  "recharts": "^2.15.3"
  "@tabler/icons-react": "^3.28.1"

catalogs:
  mantine:
    "@mantine/carousel": "^8.0.0"
    "@mantine/charts": "^8.0.0"
    "@mantine/code-highlight": "^8.0.0"
    "@mantine/core": "^8.0.0"
    "@mantine/dates": "^8.0.0"
    "@mantine/dropzone": "^8.0.0"
    "@mantine/form": "^8.0.0"
    "@mantine/hooks": "^8.0.0"
    "@mantine/modals": "^8.0.0"
    "@mantine/notifications": "^8.0.0"
    "@mantine/nprogress": "^8.0.0"
    "@mantine/spotlight": "^8.0.0"
    "@mantine/tiptap": "^8.0.0"
  nodejs:
    "@types/node": "^22.15.3"
    "@types/react": "19.1.2"
    "@types/react-dom": "19.1.3"
    "typescript": "^5.8.3"
  nextjs:
    "next": "^15.3.1"
    "react": "^19.1.0"
    "react-dom": "^19.1.0"
    "@next/bundle-analyzer": "^15.3.1"
  tiptap:
    "@tiptap/extension-link": "^2.12.0"
    "@tiptap/pm": "^2.12.0"
    "@tiptap/react": "^2.12.0"
    "@tiptap/starter-kit": "^2.12.0"
  postcss:
    "postcss": "^8.5.3"
    "postcss-preset-mantine": "^1.17.0"
    "postcss-simple-vars": "^7.0.1"
    "autoprefixer": "^10.4.21"
